year = 2020
month = 5
date = 12
goto = 5

story = """
You are [green()]still having trouble keeping up with the amount of homework[normal()] that your teachers are giving you and keeping track of them. 
# pause

Anyways, time to do some homework:(
# pause()


#"""
[[notification]]
title = "Text Notification"
text = "Ventilators and testing kit shortage in hospitals."
date = "May 12th ,2020"
