#            _  _  _                _   
#  ___ __ _ (_)| || |__  ___  __ _ | |_ 
# (_-</ _` || || || '_ \/ _ \/ _` ||  _|
# /__/\__,_||_||_||_.__/\___/\__,_| \__|
                                      
# Basic Setup:
name = "Pushing_Outshoot_Unfold"
short_name = "pushing_outshoot_unfold"
email = "po-unfold@colewilson.xyz"
author = "Cole, Harshini, Cassidy"
short_description = "A game about a teen getting through quarantine in Covid."
description = ""
url = "https://github.com/po-unfold"
keywords = ""
license = "none"
latest_build = "0.0.6"
release-notes = "fix: Unicode UTF-8 bug with encoding."
latest_release = "0.0.4"


# Resource Setup:
[resources]
icns = ""
data_files = [ "days/*.toml", "days2/*.toml", "days3/*.toml",]
modules = [ "blessed", "toml",]
file = "main.py"
no_import = [ "glob", "os", "pushing_outfold_unfold", "", "textwrap",]


# Plugin Commands:


# Build Routines:
[build.homebrew]

[build.pyinstaller]
_run = false
type = 1
mac = true
windows = true
unix = true
bundle_id = "com.pushing_outshoot_unfold.game"

[build.actions]

[build.pypi.commands]
pou = "__main__.main"

[build.pypi.entry_points]


# Release Routines:


# Other:
[git]
github = "po-unfold/game"
brew = "po-unfold/homebrew-taps"


# Thank you for using Sailboat!