#            _  _  _                _   
#  ___ __ _ (_)| || |__  ___  __ _ | |_ 
# (_-</ _` || || || '_ \/ _ \/ _` ||  _|
# /__/\__,_||_||_||_.__/\___/\__,_| \__|
                                      
# Basic Setup:
name = "Pushing_Outshoot_Unfold"
short_name = "pushing_outshoot_unfold"
email = ""
author = "Cole, Harshini, Cassidy"
short_description = "A game about a teen getting through quarantine in Covid."
description = ""
url = "https://github.com/po-unfold"
keywords = ""
license = "none"
latest_build = "0.0.2-rc1"
release-notes = "First Release, testing..."
latest_release = "0.0.1"


# Resource Setup:
[resources]
icns = ""
data_files = []
modules = [ "blessed",]
file = "main.py"
no_import = [ "toml # This reads the data files", "glob", "os # Operating system libraries",]


# Plugin Commands:


# Build Routines:
[build.homebrew]

[build.pyinstaller]
_run = false
type = 1
mac = true
windows = true
unix = true
bundle_id = "com.pushing_outshoot_unfold.game"

[build.actions]

[build.pypi.commands]
pou = "__main__.main"

[build.pypi.entry_points]


# Release Routines:


# Other:
[git]
github = "po-unfold/game"
brew = "po-unfold/homebrew-taps"


# Thank you for using Sailboat!