[[notification]]
title = "News Notification"
text = "US President Joe Biden announces a new goal of 200 million vaccinations in his administration's first 100 days (previously 100 million)."
date = "March 25th, 2021"