[[notification]]
title = "News Notificiation"
text = "The US Capitol is stormed by supporters of President Donald Trump during the congressional certification of Joe Biden and Kamala Hariris’s win. It resulted in five deaths and prompted the evacuation of lawmakers and vice president Mike Pence."
date = "January 6th, 2021"