[[notification]]
title = "News Notification"
text = "Arizona is now the COVID-19 “hotspot of the world” according to the local health officials of Arizona. There is an average of 118.3 new cases per 100,000 people."
date = "January 7th, 2021"