[[notification]]
title = "News Notification"
text = "The prime minister of Japan, Yoshihide Suga declares that Tokyo and the surrounding areas are in a state of emergency. This is due to the Covid-19 cases surging to their highest level."
date = "January 8th, 2021"