[[notification]]
title = "News Notification"
text = "More than 3000 Covid related deaths are recorded per day in America. It is the first time reaching 3,249 , passing 375,000 deaths in total a day later."
date = "January 10th, 2021"