year = 2020
month = 5
date = 25
goto = 6


story = """
You [green()]hear on the news[normal()] today that an [green()]African American man named George Floyd[normal()] had [green()]died due to police violence[normal()]. 
# normal()
# pause()

There were other violent acts against African Americans before this event, however. 
# green()

You hear about [green()]protests and riots[normal()] about the event that happened. 
# normal()

It makes you [green()]feel uncomfortable[normal()] and you [green()]feel sad[normal()] about what happened. But, you did see the posts about this event that your friends had put on their social media. 


# day5a()
"""