year = 2020
month = 6
date = 22
goto = 9

story = '''
It’s the [green()]last day of school![normal()] 

Because you didn’t get to celebrate the end of 8th grade with your friends, your parents decided to throw you a graduation party, to give some light to the end of this year. 

      _.-'`'-._
   .-'    _    '-.
    `-.__  `\_.-'
      |  `-``\|
      `-.....-\
	
# day8b()
'''