year = 2020
month = 12
date = 1
goto = 16

story = """

You’ve never had a finals before, so you’re pretty [green()]nervous for what's to come[normal()]. 

    _______
   /      /,
  /      //
 /______//
(______(/
        
# pause()

# green()
People in your zoom classes are turning on their cameras less and less. Breakout rooms are as awkward and uncomfortable as normal. Sometimes, when you try to get a conversation started, no one talks or answers, which makes things even more awkward. 
# normal()

Anyway, you have to help your sister with school now!
# pause()

# day15a()
"""