year = 2020
month = 12
date = 14#-18
goto = 17

story = '''
The final exams are here! You are supposed to only attend 3 classes a day. 
# pause()
You see that you did pretty well on your exams!

You decide to just finish up some extra credit english homework.

   ____/      452\ /     453 \____
 /| ------------- |  ------------ |\
||| ------------- | ------------- |||
||| ------------- | ------------- |||
||| ------- ----- | ------------- |||
||| ------------- | ------------- |||
||| ------------- | ------------- |||
|||  ------------ | ----------    |||
||| ------------- |  ------------ |||
||| ------------- | ------------- |||
||| ------------- | ------ -----  |||
||| ------------  | ------------- |||
|||_____________  |  _____________|||
L/_____/--------\\_//W-------\_____\J

# day16a()
'''