year = 2020
month = 12
date = 14#-18
goto = 17

story = """

There were some answers that you missed on the final exams that made you angry with yourself. That’s because on those ones, you self doubted yourself and changed your answer. 

# pause()
However, you now get a 2 and a half weeks break from school, woo-hoo!

You decide to play Would You Rather!

# day16b()

"""

