year = 2021
month = 2
date = 29# (comes after feb news string)
goto = 300

story = '''
February 29th, 2021: 

# green()
It was very shocking to hear about the winter storm in Texas. Most houses in Texas aren’t made to deal with the cold and snow like weather. So,the winter storm had taken a big toll on the state.
# normal()
# pause()

Lately, you’ve been starting to exercise more and are considering joining some school sports when schools open back up! 
     ,-"""-.
    /\     /\\
    | |   | |
    \/     \/
     '-...-'
# pause()

But, you still [green()]need to do homework[normal()].Today you have to do math, science, and english, and some P.E.
# pause()

# day20a()

You are finally done with your homework! 
# pause()

# green()
Your friend texts you!!!!!!:
# normal()

F: Hey have you heard about the new schedule?!?!?

Y: Wait, there's a new schedule??Another schedule?

F: Yeah, they are planning for people to be able to go back to school soon!

Y: That’s awesome, but how is the schedule even going to work?

F I have no idea, but I heard we would have to have classes in person and in the afternoon.

Y: Thats. . . interesting'''
