goto = 19

[[notification]]
title = "News Notificiation"
text = "The US Capitol is stormed by supporters of President Donald Trump during the congressional certification of Joe Biden and Kamala Hariris’s win. It resulted in five deaths and prompted the evacuation of lawmakers and vice president Mike Pence."
date = "January 6th, 2021"
[[notification]]
title = "News Notification"
text = "Arizona is now the COVID-19 “hotspot of the world” according to the local health officials of Arizona. There is an average of 118.3 new cases per 100,000 people."
date = "January 7th, 2021"
[[notification]]
title = "News Notification"
text = "The prime minister of Japan, Yoshihide Suga declares that Tokyo and the surrounding areas are in a state of emergency. This is due to the Covid-19 cases surging to their highest level."
date = "January 8th, 2021"
[[notification]]
title = "News Notification"
text = "More than 3000 Covid related deaths are recorded per day in America. It is the first time reaching 3,249 , passing 375,000 deaths in total a day later."
date = "January 10th, 2021"