goto = 21

[[notification]]
title = "News Notification"
text = "Prince Harry and Meghan Markle dropped bombshell accusations against Buckingham Palace in a tell-all interview with Oprah."
date = "March 7th, 2021"

[[notification]]
title = "News Notification"
text = "Gunman shoots and kills eight people at three different spas in Atlanta, Georgia during the rise of asian hate crimes"
date = "March 16th, 2021"

[[notification]]
title = "News Notification"
text = "Overseas spectators will not be allowed to attend the Tokyo Summer Olympics due to the pandemic."
date = "March 20th, 2021"

[[notification]]
title = "News Notification"
text = "10 people shot dead at a supermarket in Boulder, Colorado, by 21 year-old gunman."
date = "March 21st, 2021"

[[notification]]
title = "News Notification"
text = "US President Joe Biden announces a new goal of 200 million vaccinations in his administration's first 100 days (previously 100 million)."
date = "March 25th, 2021"